### ISSUE TITLE
Disconnection not being triggered when server is down

### ISSUE THREAD

**Issue by msqar** [ido-ofir/chat-client#2]
I'm testing server stability issues and one of them is the chat when server is down. Shouldn't this be throwing an "error" function when the socket disconnects?

I got this in my React-Native app, but is never being called.

```
// Handle errors across the chat client
                        this._chatClient.on('error', (data) => {
                            ErrorHandler.log(`Chat Client error: ${data}`);
                        });
```

Any ideas? Thanks.

**Comment by ido-ofir** [comment]
@msqar yes, it should be throwing.
I will have a look at why this happens.
in the meantime, if it helps, you could run a short timeout and check that the connection is successful then:
```js
var chatClient = new ChatClient({ url: 'ws://localhost:4001' });
// wait abit and see if it has connected
setTimeout(function() => {
    if(!chatClient.isConnected){
         alert('could not connect to chat server');
    }
}, 1000)
```

**Comment by msqar** [comment]
@ido-ofir you were right :) it was an error on my end, thanks!
